name: Create data, store it, and push back to master
'on':
  push:
    branches:
      - master
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Create data
        run: |-
          Rscript -e "source('R/create_data.R')"
      - name: Commit results
        run: |
          git add .
          git commit -m 'Add new data' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
    container: rocker/verse:latest
