name: Create data, store it, and push back to master
'on':
  push:
    branches:
      - master
#  schedule:
#    - cron:  '*/3 * * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Create data
        run: |-
          Rscript -e "source('R/create_data.R')"
      - name: Commit results
        run: |
          git commit -m "Add changes" -a
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
