name: Create data, store it, and push back to master
'on':
  push:
    branches:
      - master
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2-beta
      - name: Create data
        run: |-
          Rscript -e "source('R/create_data.R')"
      - name: Commit results
        run: |
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git config --global user.name 'Malcolm Barrett'
          git config --global user.email 'malcolmbarrett@users.noreply.github.com'
          git commit -am 'Add new data' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
    container: rocker/verse:latest
